# 各个属性的意义，见 config.Yaml 中的注释。
# 本文件只说明与测试逻辑相关的属性。
headerSize: 1024
bufferSize: 10240

# 待执行的操作，字符串，大小写不敏感，只能是以下三类之一：
# Compare：比较 compareBase 和 compareTarget。
# ScanBase：仅扫描 compareBase。
# ScanTarget：仅扫描 compareTarget。
action: "Compare"

# 虽然 compareBase 和 compareTarget 中的 needFullChecksum 均为 false，
# 但在比较时由于 HeaderChecksum 相等，所以需要 FullChecksum。所以在扫描结果文件中相等的文件，
# compareBase 中是 001.md，compareTarget 中是 010.md，这两个文件的 FullChecksum 会在比较
# 的过程中即时计算，并被保存到扫描结果中。
compareBase:
  dir: "test-data/origin/compare_base"
  scanResultFile: "test-data/output/compare-test-base.scan.json"
  loadScanResult: false
  needFullChecksum: false

compareTarget:
  dir: "test-data/origin/compare_target"
  scanResultFile: "test-data/output/compare-test-target.scan.json"
  loadScanResult: false
  needFullChecksum: false

  backupDir: "test-data/output"
  moveMore: false
  moveSame: false

filter:
  caseSensitive: false
  include:
    - "*.txt"
    - "*.md"
  exclude:
    - "*.logg"
  minFileSize: 1024
  maxFileSize: 1048576
