# 各个属性的意义，见 config.Yaml 中的注释。
# 本文件只说明与测试逻辑相关的属性。
headerSize: 1024
bufferSize: 10240

# 待执行的操作，字符串，大小写不敏感，只能是以下三类之一：
# Compare：比较 compareBase 和 compareTarget。
# ScanBase：仅扫描 compareBase。
# ScanTarget：仅扫描 compareTarget。
action: "Compare"

# 1)虽然 compareBase 和 compareTarget 中的 needFullChecksum 均为 false，
# 但在比较时由于 HeaderChecksum 相等，所以需要 FullChecksum。所以在扫描结果文件中相等的文件，
# compareBase 中是 001.md，compareTarget 中是 010.md，这两个文件的 FullChecksum 会在比较
# 的过程中即时计算，并被保存到扫描结果中。
#
# 2)由于要执行移动文件的操作，所以要准备测试用的文件，所以 compareTarget 的 dir
# 不要随便更改，它们与测试代码相关。
compareBase:
  # 相当于只读，所以可以和 compare 等测试设置相同。
  dir: "test-data/origin/compare_base"
  scanResultFile: "test-data/output/group_result/group-test-base.scan.json"
  loadScanResult: false
  needFullChecksum: false

compareTarget:
  # 由于要移动文件，所以放在可变的，不用 git 追踪的目录中。
  dir: "test-data/output/compare_target"
  scanResultFile: "test-data/output/group_result/group-test-target.scan.json"
  loadScanResult: false
  needFullChecksum: false

  compareFullChecksum: true
  backupDir: "test-data/output/group_result"
  # 如果都为 false，则不会移动，功能与仅 compare 相同。
  moveMore: true
  moveSame: true

filter:
  caseSensitive: false
  include:
    - "*.txt"
    - "*.md"
  exclude:
    - "*.logg"
  minFileSize: 1024
  maxFileSize: 1048576
